{
    'name': 'Hotel Management',
    'version': '18.0.1.0.0',
    'category': 'Services/Hotel',
    'summary': 'Hotel Management System',
    'description': """
        Hotel Management module for managing rooms, bookings, and services.
        Includes integration with Sales, Inventory and POS.
    """,
    'depends': ['base', 'sale_management', 'stock', 'point_of_sale', 'sale', 'website'],
    'data': [
        'security/hotel_security.xml',
        'security/ir.model.access.csv',
        'security/record_rule_hotel.xml',
        'security/record_rule_room.xml',
        'security/record_rule_booking.xml',
        'data/hotel_sequence.xml',
        'data/ir.cron.xml',
        'views/hotel_views.xml',
        'views/room_views.xml',
        'views/feature_views.xml',
        'views/booking_views.xml',
        'views/pending_views.xml',
        'wizards/payment_views.xml',
        # 'wizards/payment_views.xml',
        'views/menus.xml',
        'views/email_template.xml',
        'reports/hotel_reports.xml',
    ],
    'demo': [],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
